name: function-server
services:
- name: api
  environment_slug: node
  github:
    branch: main
    deploy_on_push: true
    repo: jjlesko/function_server
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "8080"