name: function-server
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: jjlesko/function_server
  build_command: npm run build
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "8080"